version: '2.1'
services:

  cc:
    build: .
    ports:
     - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cc_db
      - SPRING_DATASOURCE_USERNAME=cc
      - SPRING_DATASOURCE_PASSWORD=cc
#    healthcheck:
#      test
# curl -o - -s -w "%{http_code}\n" http://localhost
# curl -sSf http://example.org > /dev/null
# curl -s -o /dev/null -w "%{http_code}" http://www.example.org/

  postgres:
    image: postgres:10.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cc_db
      - POSTGRES_USER=cc
      - POSTGRES_PASSWORD=cc
    volumes:
      - ./database/cc:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cc"]
      interval: 5s
      timeout: 5s
      retries: 6
