spring:
  profiles.active: production

---

spring:
  profiles: production

  datasource:
    url: jdbc:postgresql://localhost:5432/cc_db
    username: cc
    password: cc
    driver-class-name: org.postgresql.Driver

liquibase:
  contexts: production

---

spring:
  profiles: development

spring.h2.console.enabled: true

liquibase:
  contexts: development
